### ISSUE TITLE
"ERROR: Cookbook apt not found" when running packer build command

### ISSUE THREAD

**Issue by maoo** [Alfresco/alfresco-spk#1]
I've followed this tutorial to integrate packer in the Chef + Vagrant logic - http://engineering.cotap.com/post/78783269747/hello-world-using-packer-chef-and-berkshelf-on-ec2

I can successfully run `packer validate packer/allinone.json` but when I run `packer build  -var 'aws_access_key=YOUR ACCESS KEY'  -var 'aws_secret_key=YOUR SECRET KEY' packer/allinone.json` I get the following error

```
    amazon-ebs: [2014-04-12T10:54:36+00:00] ERROR: Running exception handlers
    amazon-ebs: Running handlers complete
    amazon-ebs: [2014-04-12T10:54:36+00:00] ERROR: Exception handlers complete
    amazon-ebs: [2014-04-12T10:54:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    amazon-ebs: Chef Client failed. 0 resources updated in 4.73935002 seconds
    amazon-ebs: [2014-04-12T10:54:36+00:00] ERROR: Cookbook apt not found. If you're loading apt from another cookbook, make sure you configure the dependency in your metadata
    amazon-ebs:
    amazon-ebs: [2014-04-12T10:54:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Please checkout branch https://github.com/maoo/vagrant-alfresco-boxes/tree/remove-deploy-logic to reproduce the issue
